In [145]:
import MDAnalysis as mda
import pandas as pd
import numpy as np
from ast import literal_eval
from mg_sampling import PROJECT_DIR

In [236]:
converters = {f'{a}_{b}': literal_eval for a in ('inner', 'outer') for b in ('indices', 'names', 'resids', 'resnames', 'dist')}

df_pdb = pd.read_csv(PROJECT_DIR / 'structures/7ez0/mMg_tip3p/ion_motifs.csv', index_col=0, converters=converters).drop(columns=['frame', 'time']).explode([f'inner_{a}' for a in ('indices', 'names', 'resids', 'resnames', 'dist')])
df_eq = pd.read_csv(PROJECT_DIR / 'structures/7ez0/mMg_tip3p/rep00/ion_motifs.csv', index_col=0, converters=converters).drop(columns=['frame', 'time']).explode([f'inner_{a}' for a in ('indices', 'names', 'resids', 'resnames', 'dist')])

In [233]:
df_pdb.head()

,index,name,n_inner,inner_indices,inner_names,inner_resids,inner_resnames,stereo,mgrna,n_outer,outer_indices,outer_names,outer_resids,outer_resnames,inner_dist,outer_dist,origin
0,12442,MG,0,NaN,NaN,NaN,NaN,NaN,NaN,7,"[2844, 2845, 2846, 2847, 2878, 2880, 2881]","[N7, C5, C6, O6, N7, C6, O6]","[110, 110, 110, 110, 111, 111, 111]","[G, G, G, G, G, G, G]",NaN,"[4.777249163364857, 4.939364069612708, 4.80759...",pdb
1,12443,MG,1,5966,O1P,207,A,NaN,Oph,23,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 600...","[O3', P, O2P, O5', C5', H5'1, H5'2, O2P, H5'1,...","[206, 207, 207, 207, 207, 207, 207, 208, 261, ...","[A, A, A, A, A, A, A, C, A, A, A, A, C, C, C, ...",2.046801,"[4.251191152333906, 3.519446214909616, 4.45063...",pdb
2,12444,MG,0,NaN,NaN,NaN,NaN,NaN,NaN,17,"[2964, 2965, 2966, 2967, 2999, 3012, 3016, 304...","[P, O1P, O2P, O5', O2P, N7, H61, N7, C6, O6, O...","[114, 114, 114, 114, 115, 115, 115, 116, 116, ...","[A, A, A, A, A, A, A, G, G, G, G, C, C, U, A, ...",NaN,"[3.844598342218218, 3.818726868881393, 3.04923...",pdb
3,12445,MG,3,5226,O1P,184,A,fac,fac-3Oph,38,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, U, ...",1.801855,"[4.7477482312299735, 4.096449019448306, 4.1925...",pdb
3,12445,MG,3,5289,O1P,186,A,fac,fac-3Oph,38,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, U, ...",1.832862,"[4.7477482312299735, 4.096449019448306, 4.1925...",pdb

In [ ]:
df = pd.merge(df_pdb, df_eq, on=['index', 'name', 'inner_indices', 'inner_names', 'inner_resids', 'inner_resnames'], suffixes=('_pdb', '_eq'), how='outer')
df['pdb_resid'] = df['index'] - 12442 + 501

In [235]:
df.head()

,index,name,n_inner_pdb,inner_indices,inner_names,inner_resids,inner_resnames,stereo_pdb,mgrna_pdb,n_outer_pdb,...,stereo_eq,mgrna_eq,n_outer_eq,outer_indices_eq,outer_names_eq,outer_resids_eq,outer_resnames_eq,inner_dist_eq,outer_dist_eq,pdb_resid
0,12442,MG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,"[2844, 2846, 2847, 2878, 2881]","[N7, C6, O6, N7, O6]","[110, 110, 110, 111, 111]","[G, G, G, G, G]",NaN,"[4.689783616135827, 4.871000352885786, 4.38764...",501
1,12442,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501
2,12443,MG,NaN,5966,O1P,207,A,NaN,NaN,NaN,...,cis,cis-2Oph,19.0,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 771...","[O3', P, O2P, O5', C5', H5'1, H5'2, C3', H3', ...","[206, 207, 207, 207, 207, 207, 207, 261, 261, ...","[A, A, A, A, A, A, A, A, A, A, C, C, C, C, C, ...",2.088371,"[3.9570192576515866, 3.48575267198471, 4.53002...",502
3,12443,MG,1.0,5966,O1P,207,A,NaN,Oph,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,502
4,12443,MG,NaN,7723,O2P,262,C,NaN,NaN,NaN,...,cis,cis-2Oph,19.0,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 771...","[O3', P, O2P, O5', C5', H5'1, H5'2, C3', H3', ...","[206, 207, 207, 207, 207, 207, 207, 261, 261, ...","[A, A, A, A, A, A, A, A, A, A, C, C, C, C, C, ...",2.087439,"[3.9570192576515866, 3.48575267198471, 4.53002...",502

In [229]:
def get_outer_inner_dist(df):
    outer_indices = df['outer_indices_pdb']
    if isinstance(outer_indices, list):
        inner_index = df['inner_indices']
        if inner_index in outer_indices:
            i = outer_indices.index(inner_index)
            return df['outer_dist_pdb'][i]
        else:
            return np.nan
    else:
        return np.nan

df['outer_dist'] = df.apply(get_outer_inner_dist, axis=1)

In [231]:
df

,index,name,n_inner_pdb,inner_indices,inner_names,inner_resids,inner_resnames,stereo_pdb,mgrna_pdb,n_outer_pdb,...,mgrna_eq,n_outer_eq,outer_indices_eq,outer_names_eq,outer_resids_eq,outer_resnames_eq,inner_dist_eq,outer_dist_eq,pdb_resid,outer_dist
0,12442,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501,NaN
1,12443,MG,1.0,5966,O1P,207,A,NaN,Oph,23.0,...,cis-2Oph,19.0,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 771...","[O3', P, O2P, O5', C5', H5'1, H5'2, C3', H3', ...","[206, 207, 207, 207, 207, 207, 207, 261, 261, ...","[A, A, A, A, A, A, A, A, A, A, C, C, C, C, C, ...",2.088371,"[3.9570192576515866, 3.48575267198471, 4.53002...",502,NaN
2,12443,MG,NaN,7723,O2P,262,C,NaN,NaN,NaN,...,cis-2Oph,19.0,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 771...","[O3', P, O2P, O5', C5', H5'1, H5'2, C3', H3', ...","[206, 207, 207, 207, 207, 207, 207, 261, 261, ...","[A, A, A, A, A, A, A, A, A, A, C, C, C, C, C, ...",2.087439,"[3.9570192576515866, 3.48575267198471, 4.53002...",502,NaN
3,12444,MG,NaN,2966,O2P,114,A,NaN,NaN,NaN,...,Oph,17.0,"[2957, 2958, 2960, 2963, 2964, 2965, 2967, 299...","[C3', H3', H2'1, O3', P, O1P, O5', O2P, N7, H6...","[113, 113, 113, 113, 114, 114, 114, 115, 115, ...","[A, A, A, A, A, A, A, A, A, A, G, C, U, A, A, ...",2.043524,"[4.895651492092105, 4.666057508870881, 4.55299...",503,NaN
4,12444,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,503,NaN
5,12445,MG,3.0,5226,O1P,184,A,fac,fac-3Oph,38.0,...,Cis-4Oph,39.0,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, A, ...",1.976489,"[4.498715636126078, 4.328519406282848, 3.86726...",504,NaN
6,12445,MG,3.0,5289,O1P,186,A,fac,fac-3Oph,38.0,...,Cis-4Oph,39.0,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, A, ...",2.146132,"[4.498715636126078, 4.328519406282848, 3.86726...",504,NaN
7,12445,MG,3.0,5323,O2P,187,A,fac,fac-3Oph,38.0,...,Cis-4Oph,39.0,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, A, ...",2.035714,"[4.498715636126078, 4.328519406282848, 3.86726...",504,NaN
8,12445,MG,NaN,5356,O2P,188,G,NaN,NaN,NaN,...,Cis-4Oph,39.0,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","[O1P, H5'2, O3', P, O2P, O5', C5', H5'1, H5'2,...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","[A, A, A, A, A, A, A, A, A, U, U, U, U, U, A, ...",2.071137,"[4.498715636126078, 4.328519406282848, 3.86726...",504,NaN
9,12446,MG,3.0,5193,O1P,183,A,fac,fac-3Oph,30.0,...,fac-3Oph,29.0,"[3792, 3793, 3794, 5191, 5192, 5194, 5195, 519...","[C2, H2, N3, O3', P, O2P, O5', C5', H5'2, H8, ...","[139, 139, 139, 182, 183, 183, 183, 183, 183, ...","[A, A, A, U, A, A, A, A, A, A, A, A, A, A, A, ...",2.14842,"[4.717939731473786, 4.315144056230363, 4.90992...",505,NaN
10,12446,MG,3.0,5227,O2P,184,A,fac,fac-3Oph,30.0,...,fac-3Oph,29.0,"[3792, 3793, 3794, 5191, 5192, 5194, 5195, 519...","[C2, H2, N3, O3', P, O2P, O5', C5', H5'2, H8, ...","[139, 139, 139, 182, 183, 183, 183, 183, 183, ...","[A, A, A, U, A, A, A, A, A, A, A, A, A, A, A, ...",2.015739,"[4.717939731473786, 4.315144056230363, 4.90992...",505,NaN
11,12446,MG,3.0,5290,O2P,186,A,fac,fac-3Oph,30.0,...,fac-3Oph,29.0,"[3792, 3793, 3794, 5191, 5192, 5194, 5195, 519...","[C2, H2, N3, O3', P, O2P, O5', C5', H5'2, H8, ...","[139, 139, 139, 182, 183, 183, 183, 183, 183, ...","[A, A, A, U, A, A, A, A, A, A, A, A, A, A, A, ...",2.061092,"[4.717939731473786, 4.315144056230363, 4.90992...",505,NaN
12,12447,MG,NaN,4645,O1P,166,C,NaN,NaN,NaN,...,cis-2Oph,23.0,"[4614, 4617, 4619, 4637, 4638, 4643, 4644, 464...","[O1P, C5', H5'2, C3', H3', O3', P, O2P, O5', C...","[165, 165, 165, 165, 165, 165, 166, 166, 166, ...","[C, C, C, C, C, C, C, C, C, U, U, U, U, U, U, ...",2.231703,"[4.8578384056631485, 4.972594290221921, 4.0365...",506,NaN
13,12447,MG,NaN,4706,O1P,168,U,NaN,NaN,NaN,...,cis-2Oph,23.0,"[4614, 4617, 4619, 4637, 4638, 4643, 4644, 464...","[O1P, C5', H5'2, C3', H3', O3', P, O2P, O5', C...","[165, 165, 165, 165, 165, 165, 166, 166, 166, ...","[C, C, C, C, C, C, C, C, C, U, U, U, U, U, U, ...",2.190278,"[4.8578384056631485, 4.972594290221921, 4.0365...",506,NaN
14,12447,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506,NaN
15,12448,MG,NaN,4547,O2P,163,G,NaN,NaN,NaN,...,Oph,25.0,"[4515, 4516, 4517, 4518, 4521, 4538, 4539, 454...","[P, O1P, O2P, O5', H5'2, C3', H3', O3', P, O1P...","[162, 162, 162, 162, 162, 162, 162, 162, 163, ...","[U, U, U, U, U, U, U, U, G, G, G, G, G, G, G, ...",2.113013,"[4.863592410064554, 4.710471096250343, 4.66370...",507,NaN
16,12448,MG,1.0,4597,O6,164,G,NaN,Ob,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,507,NaN
17,12449,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,508,NaN
18,12450,MG,NaN,4309,O4,155,U,NaN,NaN,NaN,...,Ob,16.0,"[4043, 4076, 4077, 4111, 4277, 4278, 4279, 428...","[O6, C6, O6, O6, C4, N4, H41, H42, C5, H5, C4,...","[147, 148, 148, 149, 154, 154, 154, 154, 155, ...","[G, G, G, G, C, C, C, C, U, U, U, U, U, U, U, U]",2.167973,"[4.756610745027691, 4.990348420319253, 3.84191...",509,NaN
19,12450,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,509,NaN
20,12451,MG,1.0,4095,O2P,149,G,NaN,Oph,14.0,...,Oph,15.0,"[4061, 4086, 4087, 4092, 4093, 4094, 4096, 410...","[O2P, C3', H3', O3', P, O1P, O5', C8, H8, N7, ...","[148, 148, 148, 148, 149, 149, 149, 149, 149, ...","[G, G, G, G, G, G, G, G, G, G, G, G, G, G, G]",2.082837,"[4.900323248450624, 4.690102554770957, 3.95858...",510,NaN
21,12452,MG,1.0,7531,O1P,256,A,NaN,Oph,16.0,...,cis-2Oph,15.0,"[7507, 7529, 7530, 7532, 7533, 7543, 7544, 754...","[H4', O3', P, O2P, O5', C8, H8, N7, O3', P, O2...","[255, 255, 256, 256, 256, 256, 256, 256, 272, ...","[C, C, A, A, A, A, A, A, G, U, U, U, U, U, C]",2.158794,"[4.350248179503873, 4.031948663459229, 3.58494...",511,NaN
22,12452,MG,NaN,8077,O1P,273,U,NaN,NaN,NaN,...,cis-2Oph,15.0,"[7507, 7529, 7530, 7532, 7533, 7543, 7544, 754...","[H4', O3', P, O2P, O5', C8, H8, N7, O3', P, O2...","[255, 255, 256, 256, 256, 256, 256, 256, 272, ...","[C, C, A, A, A, A, A, A, G, U, U, U, U, U, C]",2.078964,"[4.350248179503873, 4.031948663459229, 3.58494...",511,NaN
23,12453,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512,NaN
24,12454,MG,NaN,6289,O2P,217,C,NaN,NaN,NaN,...,Oph,18.0,"[6256, 6257, 6258, 6259, 6262, 6270, 6280, 628...","[P, O1P, O2P, O5', H5'2, H6, C3', H3', O3', P,...","[216, 216, 216, 216, 216, 216, 216, 216, 216, ...","[C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...",2.029508,"[4.6522009998770875, 4.608487095217344, 4.3797...",513,NaN
25,12454,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,513,NaN
26,12455,MG,1.0,6191,O2P,214,A,NaN,Oph,17.0,...,Oph,14.0,"[6158, 6159, 6160, 6161, 6172, 6182, 6183, 618...","[P, O1P, O2P, O5', H6, C3', H3', O3', P, O1P, ...","[213, 213, 213, 213, 213, 213, 213, 213, 214, ...","[C, C, C, C, C, C, C, C, A, A, A, A, A, A]",2.044626,"[4.638741709440494, 4.922121380766013, 4.07977...",514,NaN
27,12456,MG,NaN,7564,O1P,257,G,NaN,NaN,NaN,...,Cis-3OphOb,27.0,"[7562, 7563, 7565, 7566, 7567, 7569, 7590, 759...","[O3', P, O2P, O5', C5', H5'2, C3', H3', O3', P...","[256, 257, 257, 257, 257, 257, 257, 257, 257, ...","[A, G, G, G, G, G, G, G, G, U, U, U, U, U, U, ...",2.17322,"[4.569382640335183, 3.3772480040204997, 3.7396...",515,NaN
28,12456,MG,2.0,7599,O2P,258,U,cis,cis-2Oph,29.0,...,Cis-3OphOb,27.0,"[7562, 7563, 7565, 7566, 7567, 7569, 7590, 759...","[O3', P, O2P, O5', C5', H5'2, C3', H3', O3', P...","[256, 257, 257, 257, 257, 257, 257, 257, 257, ...","[A, G, G, G, G, G, G, G, G, U, U, U, U, U, U, ...",2.081972,"[4.569382640335183, 3.3772480040204997, 3.7396...",515,NaN
29,12456,MG,NaN,7680,O2,260,C,NaN,NaN,NaN,...,Cis-3OphOb,27.0,"[7562, 7563, 7565, 7566, 7567, 7569, 7590, 759...","[O3', P, O2P, O5', C5', H5'2, C3', H3', O3', P...","[256, 257, 257, 257, 257, 257, 257, 257, 257, ...","[A, G, G, G, G, G, G, G, G, U, U, U, U, U, U, ...",2.335935,"[4.569382640335183, 3.3772480040204997, 3.7396...",515,NaN
30,12456,MG,2.0,9103,O2P,305,U,cis,cis-2Oph,29.0,...,Cis-3OphOb,27.0,"[7562, 7563, 7565, 7566, 7567, 7569, 7590, 759...","[O3', P, O2P, O5', C5', H5'2, C3', H3', O3', P...","[256, 257, 257, 257, 257, 257, 257, 257, 257, ...","[A, G, G, G, G, G, G, G, G, U, U, U, U, U, U, ...",2.101835,"[4.569382640335183, 3.3772480040204997, 3.7396...",515,NaN
31,12457,MG,NaN,7598,O1P,258,U,NaN,NaN,NaN,...,fac-3Oph,29.0,"[7596, 7597, 7599, 7600, 7601, 7602, 7603, 760...","[O3', P, O2P, O5', C5', H5'1, H5'2, C4', C3', ...","[257, 258, 258, 258, 258, 258, 258, 258, 258, ...","[G, U, U, U, U, U, U, U, U, U, U, U, U, U, C, ...",2.154744,"[4.598884245358015, 3.458674501345328, 4.12536...",516,NaN
32,12457,MG,NaN,7629,O2P,259,U,NaN,NaN,NaN,...,fac-3Oph,29.0,"[7596, 7597, 7599, 7600, 7601, 7602, 7603, 760...","[O3', P, O2P, O5', C5', H5'1, H5'2, C4', C3', ...","[257, 258, 258, 258, 258, 258, 258, 258, 258, ...","[G, U, U, U, U, U, U, U, U, U, U, U, U, U, C, ...",2.239241,"[4.598884245358015, 3.458674501345328, 4.12536...",516,NaN
33,12457,MG,NaN,7690,O2P,261,A,NaN,NaN,NaN,...,fac-3Oph,29.0,"[7596, 7597, 7599, 7600, 7601, 7602, 7603, 760...","[O3', P, O2P, O5', C5', H5'1, H5'2, C4', C3', ...","[257, 258, 258, 258, 258, 258, 258, 258, 258, ...","[G, U, U, U, U, U, U, U, U, U, U, U, U, U, C, ...",2.009455,"[4.598884245358015, 3.458674501345328, 4.12536...",516,NaN
34,12457,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,516,NaN
35,12458,MG,1.0,7628,O1P,259,U,NaN,Oph,24.0,...,cis-2Oph,24.0,"[7626, 7627, 7629, 7630, 7631, 7632, 7633, 766...","[O3', P, O2P, O5', C5', H5'1, H5'2, H5'2, C3',...","[258, 259, 259, 259, 259, 259, 259, 260, 260, ...","[U, U, U, U, U, U, U, C, C, C, C, A, A, A, A, ...",2.130982,"[4.643368550807623, 3.486799027993048, 4.23604...",517,NaN
36,12458,MG,NaN,7689,O1P,261,A,NaN,NaN,NaN,...,cis-2Oph,24.0,"[7626, 7627, 7629, 7630, 7631, 7632, 7633, 766...","[O3', P, O2P, O5', C5', H5'1, H5'2, H5'2, C3',...","[258, 259, 259, 259, 259, 259, 259, 260, 260, ...","[U, U, U, U, U, U, U, C, C, C, C, A, A, A, A, ...",2.104617,"[4.643368550807623, 3.486799027993048, 4.23604...",517,NaN
37,12459,MG,NaN,9102,O1P,305,U,NaN,NaN,NaN,...,Oph,18.0,"[7541, 7553, 7554, 7562, 7564, 9035, 9039, 909...","[H1', H2, N3, O3', O1P, O1P, H5'1, C3', H3', C...","[256, 256, 256, 256, 257, 303, 303, 304, 304, ...","[A, A, A, A, G, G, G, A, A, A, A, A, A, U, U, ...",2.164256,"[4.363797570882349, 4.921924084922768, 4.76393...",518,NaN
38,12459,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,518,NaN
39,12460,MG,2.0,8969,O1P,301,A,cis,cis-2Oph,30.0,...,cis-2Oph,31.0,"[7547, 7548, 7549, 7550, 7551, 8019, 8020, 802...","[C6, N6, H61, H62, N1, C4', H4', O4', P, O1P, ...","[256, 256, 256, 256, 256, 271, 271, 271, 272, ...","[A, A, A, A, A, U, U, U, G, G, U, U, U, U, U, ...",2.036789,"[4.892975366762165, 4.153095516000277, 4.77858...",519,NaN
40,12460,MG,2.0,9003,O2P,302,A,cis,cis-2Oph,30.0,...,cis-2Oph,31.0,"[7547, 7548, 7549, 7550, 7551, 8019, 8020, 802...","[C6, N6, H61, H62, N1, C4', H4', O4', P, O1P, ...","[256, 256, 256, 256, 256, 271, 271, 271, 272, ...","[A, A, A, A, A, U, U, U, G, G, U, U, U, U, U, ...",2.084924,"[4.892975366762165, 4.153095516000277, 4.77858...",519,NaN
41,12461,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520,NaN
42,12462,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521,NaN
43,12463,MG,NaN,4770,O1P,170,C,NaN,NaN,NaN,...,cis-2Oph,21.0,"[4704, 4707, 4709, 4710, 4711, 4768, 4769, 477...","[O3', O2P, C5', H5'1, H5'2, O3', P, O2P, O5', ...","[167, 168, 168, 168, 168, 169, 170, 170, 170, ...","[U, U, U, U, U, G, C, C, C, C, C, C, C, C, C, ...",2.203523,"[4.938231011582556, 4.175211589590309, 4.54030...",522,NaN
44,12463,MG,1.0,4802,O2P,171,A,NaN,Oph,18.0,...,cis-2Oph,21.0,"[4704, 4707, 4709, 4710, 4711, 4768, 4769, 477...","[O3', O2P, C5', H5'1, H5'2, O3', P, O2P, O5', ...","[167, 168, 168, 168, 168, 169, 170, 170, 170, ...","[U, U, U, U, U, G, C, C, C, C, C, C, C, C, C, ...",2.073411,"[4.938231011582556, 4.175211589590309, 4.54030...",522,NaN
45,12464,MG,1.0,4835,O2P,172,A,NaN,Oph,22.0,...,cis-2Oph,22.0,"[4826, 4827, 4830, 4831, 4832, 4833, 4834, 483...","[C3', H3', O2', HO'2, O3', P, O1P, O5', C5', H...","[171, 171, 171, 171, 171, 172, 172, 172, 172, ...","[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",2.179313,"[4.6011818770523805, 4.880783646297851, 4.4044...",523,NaN
46,12464,MG,NaN,4868,O2P,173,A,NaN,NaN,NaN,...,cis-2Oph,22.0,"[4826, 4827, 4830, 4831, 4832, 4833, 4834, 483...","[C3', H3', O2', HO'2, O3', P, O1P, O5', C5', H...","[171, 171, 171, 171, 171, 172, 172, 172, 172, ...","[A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, ...",2.055653,"[4.6011818770523805, 4.880783646297851, 4.4044...",523,NaN
47,12465,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524,NaN
48,12466,MG,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,525,NaN
49,12467,MG,NaN,5999,O1P,208,C,NaN,NaN,NaN,...,fac-3Oph,20.0,"[5997, 5998, 6000, 6001, 9066, 9067, 9068, 907...","[O3', P, O2P, O5', HO'2, O3', P, O2P, O5', C5'...","[207, 208, 208, 208, 303, 303, 304, 304, 304, ...","[A, C, C, C, G, G, A, A, A, A, A, A, U, U, U, ...",2.205742,"[4.538520096866263, 3.7056467156283075, 4.5409...",526,NaN
50,12467,MG,NaN,9069,O1P,304,A,NaN,NaN,NaN,...,fac-3Oph,20.0,"[5997, 5998, 6000, 6001, 9066, 9067, 9068, 907...","[O3', P, O2P, O5', HO'2, O3', P, O2P, O5', C5'...","[207, 208, 208, 208, 303, 303, 304, 304, 304, ...","[A, C, C, C, G, G, A, A, A, A, A, A, U, U, U, ...",2.059945,"[4.538520096866263, 3.7056467156283075, 4.5409...",526,NaN
51,12467,MG,1.0,9132,O1P,306,A,NaN,Oph,17.0,...,fac-3Oph,20.0,"[5997, 5998, 6000, 6001, 9066, 9067, 9068, 907...","[O3', P, O2P, O5', HO'2, O3', P, O2P, O5', C5'...","[207, 208, 208, 208, 303, 303, 304, 304, 304, ...","[A, C, C, C, G, G, A, A, A, A, A, A, U, U, U, ...",2.143665,"[4.538520096866263, 3.7056467156283075, 4.5409...",526,NaN
52,12468,MG,2.0,9166,O2P,307,U,cis,cis-2Oph,23.0,...,cis-2Oph,19.0,"[9142, 9157, 9161, 9163, 9164, 9165, 9167, 916...","[H1', C3', O2', O3', P, O1P, O5', C5', H5'2, C...","[306, 306, 306, 306, 307, 307, 307, 307, 307, ...","[A, A, A, A, U, U, U, U, U, U, U, U, U, A, A, ...",2.091147,"[4.948875886185387, 4.924841351693477, 4.71170...",527,NaN
53,12468,MG,2.0,9196,O2P,308,A,cis,cis-2Oph,23.0,...,cis-2Oph,19.0,"[9142, 9157, 9161, 9163, 9164, 9165, 9167, 916...","[H1', C3', O2', O3', P, O1P, O5', C5', H5'2, C...","[306, 306, 306, 306, 307, 307, 307, 307, 307, ...","[A, A, A, A, U, U, U, U, U, U, U, U, U, A, A, ...",2.067585,"[4.948875886185387, 4.924841351693477, 4.71170...",527,NaN

In [191]:
df['outer_to_inner'] = df.apply(lambda x: x['inner_indices'] if x['inner_indices'] in x['outer_indices_pdb'] else np.nan)

KeyError: 'inner_indices'

In [152]:
df

,index,name,n_inner_pdb,inner_indices_pdb,inner_names_pdb,inner_resids_pdb,inner_resnames_pdb,stereo_pdb,mgrna_pdb,n_outer_pdb,...,n_outer_eq,outer_indices_eq,outer_names_eq,outer_resids_eq,outer_resnames_eq,inner_dist_eq,outer_dist_eq,inner_labels_eq,pdb_resid,outer_to_inner
0,12442,MG,0,[],[],[],[],NaN,NaN,7,...,5,"[2844, 2846, 2847, 2878, 2881]","['N7', 'C6', 'O6', 'N7', 'O6']","[110, 110, 110, 111, 111]","['G', 'G', 'G', 'G', 'G']",,"[4.689783616135827, 4.871000352885786, 4.38764...",,501,
1,12443,MG,1,[5966],['O1P'],[207],['A'],NaN,Oph,23,...,19,"[5964, 5965, 5967, 5968, 5969, 5970, 5971, 771...","[""O3'"", 'P', 'O2P', ""O5'"", ""C5'"", ""H5'1"", ""H5'...","[206, 207, 207, 207, 207, 207, 207, 261, 261, ...","['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', ...",2.1\newline2.1,"[3.9570192576515866, 3.48575267198471, 4.53002...",$^{207}$A:O1P\newline$^{262}$C:O2P,502,$^{262}$C:O2P (2.5 Å)
2,12444,MG,0,[],[],[],[],NaN,NaN,17,...,17,"[2957, 2958, 2960, 2963, 2964, 2965, 2967, 299...","[""C3'"", ""H3'"", ""H2'1"", ""O3'"", 'P', 'O1P', ""O5'...","[113, 113, 113, 113, 114, 114, 114, 115, 115, ...","['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', ...",2.0,"[4.895651492092105, 4.666057508870881, 4.55299...",$^{114}$A:O2P,503,$^{114}$A:O2P (3.0 Å)
3,12445,MG,3,"[5226, 5289, 5323]","['O1P', 'O1P', 'O2P']","[184, 186, 187]","['A', 'A', 'A']",fac,fac-3Oph,38,...,39,"[5193, 5198, 5224, 5225, 5227, 5228, 5229, 523...","['O1P', ""H5'2"", ""O3'"", 'P', 'O2P', ""O5'"", ""C5'...","[183, 183, 183, 184, 184, 184, 184, 184, 184, ...","['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', ...",2.0\newline2.1\newline2.0\newline2.1,"[4.498715636126078, 4.328519406282848, 3.86726...",$^{184}$A:O1P\newline$^{186}$A:O1P\newline$^{1...,504,$^{188}$G:O2P (3.5 Å)
4,12446,MG,3,"[5193, 5227, 5290]","['O1P', 'O2P', 'O2P']","[183, 184, 186]","['A', 'A', 'A']",fac,fac-3Oph,30,...,29,"[3792, 3793, 3794, 5191, 5192, 5194, 5195, 519...","['C2', 'H2', 'N3', ""O3'"", 'P', 'O2P', ""O5'"", ""...","[139, 139, 139, 182, 183, 183, 183, 183, 183, ...","['A', 'A', 'A', 'U', 'A', 'A', 'A', 'A', 'A', ...",2.1\newline2.0\newline2.1,"[4.717939731473786, 4.315144056230363, 4.90992...",$^{183}$A:O1P\newline$^{184}$A:O2P\newline$^{1...,505,
5,12447,MG,0,[],[],[],[],NaN,NaN,24,...,23,"[4614, 4617, 4619, 4637, 4638, 4643, 4644, 464...","['O1P', ""C5'"", ""H5'2"", ""C3'"", ""H3'"", ""O3'"", 'P...","[165, 165, 165, 165, 165, 165, 166, 166, 166, ...","['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', ...",2.2\newline2.2,"[4.8578384056631485, 4.972594290221921, 4.0365...",$^{166}$C:O1P\newline$^{168}$U:O1P,506,$^{166}$C:O1P (4.7 Å)\newline$^{168}$U:O1P (3....
6,12448,MG,1,[4597],['O6'],[164],['G'],NaN,Ob,24,...,25,"[4515, 4516, 4517, 4518, 4521, 4538, 4539, 454...","['P', 'O1P', 'O2P', ""O5'"", ""H5'2"", ""C3'"", ""H3'...","[162, 162, 162, 162, 162, 162, 162, 162, 163, ...","['U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'G', ...",2.1,"[4.863592410064554, 4.710471096250343, 4.66370...",$^{163}$G:O2P,507,$^{163}$G:O2P (4.0 Å)
7,12449,MG,0,[],[],[],[],NaN,NaN,10,...,9,"[3770, 3771, 3772, 4497, 4500, 4501, 4502, 453...","['P', 'O1P', 'O2P', 'N7', 'N6', 'H61', 'H62', ...","[139, 139, 139, 161, 161, 161, 161, 162, 162]","['A', 'A', 'A', 'A', 'A', 'A', 'A', 'U', 'U']",,"[4.752125064403985, 3.980874307438456, 4.38810...",,508,
8,12450,MG,0,[],[],[],[],NaN,NaN,11,...,16,"[4043, 4076, 4077, 4111, 4277, 4278, 4279, 428...","['O6', 'C6', 'O6', 'O6', 'C4', 'N4', 'H41', 'H...","[147, 148, 148, 149, 154, 154, 154, 154, 155, ...","['G', 'G', 'G', 'G', 'C', 'C', 'C', 'C', 'U', ...",2.2,"[4.756610745027691, 4.990348420319253, 3.84191...",$^{155}$U:O4,509,$^{155}$U:O4 (4.4 Å)
9,12451,MG,1,[4095],['O2P'],[149],['G'],NaN,Oph,14,...,15,"[4061, 4086, 4087, 4092, 4093, 4094, 4096, 410...","['O2P', ""C3'"", ""H3'"", ""O3'"", 'P', 'O1P', ""O5'""...","[148, 148, 148, 148, 149, 149, 149, 149, 149, ...","['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', ...",2.1,"[4.900323248450624, 4.690102554770957, 3.95858...",$^{149}$G:O2P,510,
10,12452,MG,1,[7531],['O1P'],[256],['A'],NaN,Oph,16,...,15,"[7507, 7529, 7530, 7532, 7533, 7543, 7544, 754...","[""H4'"", ""O3'"", 'P', 'O2P', ""O5'"", 'C8', 'H8', ...","[255, 255, 256, 256, 256, 256, 256, 256, 272, ...","['C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'G', ...",2.2\newline2.1,"[4.350248179503873, 4.031948663459229, 3.58494...",$^{256}$A:O1P\newline$^{273}$U:O1P,511,$^{273}$U:O1P (2.5 Å)
11,12453,MG,0,[],[],[],[],NaN,NaN,6,...,12,"[2434, 8186, 8187, 8188, 8189, 8223, 8253, 825...","['H61', 'N7', 'C5', 'C6', 'O6', 'O4', 'N4', 'H...","[97, 276, 276, 276, 276, 277, 278, 278, 278, 3...","['A', 'G', 'G', 'G', 'G', 'U', 'C', 'C', 'C', ...",,"[4.986738430320389, 4.319848205244726, 4.94393...",,512,
12,12454,MG,0,[],[],[],[],NaN,NaN,21,...,18,"[6256, 6257, 6258, 6259, 6262, 6270, 6280, 628...","['P', 'O1P', 'O2P', ""O5'"", ""H5'2"", 'H6', ""C3'""...","[216, 216, 216, 216, 216, 216, 216, 216, 216, ...","['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', ...",2.0,"[4.6522009998770875, 4.608487095217344, 4.3797...",$^{217}$C:O2P,513,$^{217}$C:O2P (3.4 Å)
13,12455,MG,1,[6191],['O2P'],[214],['A'],NaN,Oph,17,...,14,"[6158, 6159, 6160, 6161, 6172, 6182, 6183, 618...","['P', 'O1P', 'O2P', ""O5'"", 'H6', ""C3'"", ""H3'"",...","[213, 213, 213, 213, 213, 213, 213, 213, 214, ...","['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'A', ...",2.0,"[4.638741709440494, 4.922121380766013, 4.07977...",$^{214}$A:O2P,514,
14,12456,MG,2,"[7599, 9103]","['O2P', 'O2P']","[258, 305]","['U', 'U']",cis,cis-2Oph,29,...,27,"[7562, 7563, 7565, 7566, 7567, 7569, 7590, 759...","[""O3'"", 'P', 'O2P', ""O5'"", ""C5'"", ""H5'2"", ""C3'...","[256, 257, 257, 257, 257, 257, 257, 257, 257, ...","['A', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', ...",2.2\newline2.1\newline2.3\newline2.1,"[4.569382640335183, 3.3772480040204997, 3.7396...",$^{257}$G:O1P\newline$^{258}$U:O2P\newline$^{2...,515,$^{257}$G:O1P (2.6 Å)\newline$^{260}$C:O2 (2.7 Å)
15,12457,MG,0,[],[],[],[],NaN,NaN,24,...,29,"[7596, 7597, 7599, 7600, 7601, 7602, 7603, 760...","[""O3'"", 'P', 'O2P', ""O5'"", ""C5'"", ""H5'1"", ""H5'...","[257, 258, 258, 258, 258, 258, 258, 258, 258, ...","['G', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', ...",2.2\newline2.2\newline2.0,"[4.598884245358015, 3.458674501345328, 4.12536...",$^{258}$U:O1P\newline$^{259}$U:O2P\newline$^{2...,516,$^{258}$U:O1P (2.5 Å)\newline$^{259}$U:O2P (4....
16,12458,MG,1,[7628],['O1P'],[259],['U'],NaN,Oph,24,...,24,"[7626, 7627, 7629, 7630, 7631, 7632, 7633, 766...","[""O3'"", 'P', 'O2P', ""O5'"", ""C5'"", ""H5'1"", ""H5'...","[258, 259, 259, 259, 259, 259, 259, 260, 260, ...","['U', 'U', 'U', 'U', 'U', 'U', 'U', 'C', 'C', ...",2.1\newline2.1,"[4.643368550807623, 3.486799027993048, 4.23604...",$^{259}$U:O1P\newline$^{261}$A:O1P,517,$^{261}$A:O1P (3.7 Å)
17,12459,MG,0,[],[],[],[],NaN,NaN,19,...,18,"[7541, 7553, 7554, 7562, 7564, 9035, 9039, 909...","[""H1'"", 'H2', 'N3', ""O3'"", 'O1P', 'O1P', ""H5'1...","[256, 256, 256, 256, 257, 303, 303, 304, 304, ...","['A', 'A', 'A', 'A', 'G', 'G', 'G', 'A', 'A', ...",2.2,"[4.363797570882349, 4.921924084922768, 4.76393...",$^{305}$U:O1P,518,$^{305}$U:O1P (2.6 Å)
18,12460,MG,2,"[8969, 9003]","['O1P', 'O2P']","[301, 302]","['A', 'A']",cis,cis-2Oph,30,...,31,"[7547, 7548, 7549, 7550, 7551, 8019, 8020, 802...","['C6', 'N6', 'H61', 'H62', 'N1', ""C4'"", ""H4'"",...","[256, 256, 256, 256, 256, 271, 271, 271, 272, ...","['A', 'A', 'A', 'A', 'A', 'U', 'U', 'U', 'G', ...",2.0\newline2.1,"[4.892975366762165, 4.153095516000277, 4.77858...",$^{301}$A:O1P\newline$^{302}$A:O2P,519,
19,12461,MG,0,[],[],[],[],NaN,NaN,13,...,12,"[334, 339, 366, 367, 368, 369, 8912, 8913, 891...","['O1P', ""H5'2"", ""O3'"", 'P', 'O1P', 'O2P', ""C4'...","[32, 32, 32, 33, 33, 33, 299, 299, 299, 299, 2...","['G', 'G', 'G', 'U', 'U', 'U', 'A', 'A', 'A', ...",,"[4.4011992230186445, 3.957751948359475, 4.6483...",,520,
20,12462,MG,0,[],[],[],[],NaN,NaN,8,...,9,"[8315, 8316, 8317, 8318, 8349, 8352, 8383, 838...","['N7', 'C5', 'C6', 'O6', 'N7', 'O6', 'N7', 'O6...","[280, 280, 280, 280, 281, 281, 282, 282, 296]","['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'C']",,"[4.635235647080835, 4.9319858540790475, 4.8649...",,521,
21,12463,MG,1,[4802],['O2P'],[171],['A'],NaN,Oph,18,...,21,"[4704, 4707, 4709, 4710, 4711, 4768, 4769, 477...","[""O3'"", 'O2P', ""C5'"", ""H5'1"", ""H5'2"", ""O3'"", '...","[167, 168, 168, 168, 168, 169, 170, 170, 170, ...","['U', 'U', 'U', 'U', 'U', 'G', 'C', 'C', 'C', ...",2.2\newline2.1,"[4.938231011582556, 4.175211589590309, 4.54030...",$^{170}$C:O1P\newline$^{171}$A:O2P,522,$^{170}$C:O1P (4.6 Å)
22,12464,MG,1,[4835],['O2P'],[172],['A'],NaN,Oph,22,...,22,"[4826, 4827, 4830, 4831, 4832, 4833, 4834, 483...","[""C3'"", ""H3'"", ""O2'"", ""HO'2"", ""O3'"", 'P', 'O1P...","[171, 171, 171, 171, 171, 172, 172, 172, 172, ...","['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', ...",2.2\newline2.1,"[4.6011818770523805, 4.880783646297851, 4.4044...",$^{172}$A:O2P\newline$^{173}$A:O2P,523,$^{173}$A:O2P (2.6 Å)
23,12465,MG,0,[],[],[],[],NaN,NaN,15,...,17,"[663, 664, 681, 683, 684, 701, 702, 703, 704, ...","[""C1'"", ""H1'"", ""C2'"", ""O2'"", ""HO'2"", 'C5', 'H5...","[42, 42, 42, 42, 42, 43, 43, 43, 43, 167, 167,...","['A', 'A', 'A', 'A', 'A', 'U', 'U', 'U', 'U', ...",,"[4.96378368466236, 4.276641375388184, 4.950811...",,524,
24,12466,MG,0,[],[],[],[],NaN,NaN,4,...,5,"[7741, 9307, 9340, 9374, 9410]","['H42', 'H5', 'O6', 'O6', 'H62']","[262, 311, 312, 313, 314]","['C', 'C', 'G', 'G', 'A']",,"[4.826401085199991, 4.724541252555845, 4.17969...",,525,
25,12467,MG,1,[9132],['O1P'],[306],['A'],NaN,Oph,17,...,20,"[5997, 5998, 6000, 6001, 9066, 9067, 9068, 907...","[""O3'"", 'P', 'O2P', ""O5'"", ""HO'2"", ""O3'"", 'P',...","[207, 208, 208, 208, 303, 303, 304, 304, 304, ...","['A', 'C', 'C', 'C', 'G', 'G', 'A', 'A', 'A', ...",2.2\newline2.1\newline2.1,"[4.538520096866263, 3.7056467156283075, 4.5409...",$^{208}$C:O1P\newline$^{304}$A:O1P\newline$^{3...,526,$^{208}$C:O1P (3.3 Å)\newline$^{304}$A:O1P (2....
26,12468,MG,2,"[9166, 9196]","['O2P', 'O2P']","[307, 308]","['U', 'A']",cis,cis-2Oph,23,...,19,"[9142, 9157, 9161, 9163, 9164, 9165, 9167, 916...","[""H1'"", ""C3'"", ""O2'"", ""O3'"", 'P', 'O1P', ""O5'""...","[306, 306, 306, 306, 307, 307, 307, 307, 307, ...","['A', 'A', 'A', 'A', 'U', 'U', 'U', 'U', 'U', ...",2.1\newline2.1,"[4.948875886185387, 4.924841351693477, 4.71170...",$^{307}$U:O2P\newline$^{308}$A:O2P,527,

In [141]:
def format_mgrna(s):
    mapping = {
        'Oph': r'$\mathrm{O_{ph}}$',
        'Ob': r'$\mathrm{O_b}$',
        'fac': r'\textit{fac}',
        'cis': r'\textit{cis}',
        'Cis': r'\underline{\textit{Cis}}',
    }
    for k, v in mapping.items():
        s = s.replace(k, v)
    return s

header = ['Res.', 'Inner atoms', '$d$ [Å]', 'MgRNA class', 'Inner atoms', '$d$ [Å]', 'MgRNA class']
mask = (df['inner_labels_pdb'] != "") | (df['inner_labels_eq'] != "")
print(
    df[['pdb_resid', 'inner_labels_pdb', 'inner_dist_pdb', 'mgrna_pdb', 'inner_labels_eq', 'inner_dist_eq', 'mgrna_eq']].loc[mask].replace("", "--").to_latex(
        index=False,
        header=header,
        column_format='l|XXl|XXl',
        na_rep="--",
        formatters={
            'pdb_resid': lambda x: f"\hline {x}",
            'mgrna_pdb': format_mgrna,
            'mgrna_eq': format_mgrna,
        },
    ).replace(r'\begin{tabular}', r'\begin{tabularx}{\linewidth}').replace(r'\end{tabular}', r'\end{tabularx}').replace(r'\toprule', r'\toprule & \multicolumn{3}{c|}{\textbf{PDB}} & \multicolumn{3}{c}{\textbf{After NPT equilibration}} \\')
)

\begin{tabularx}{\linewidth}{l|XXl|XXl}
\toprule & \multicolumn{3}{c|}{\textbf{PDB}} & \multicolumn{3}{c}{\textbf{After NPT equilibration}} \\
Res. & Inner atoms & $d$ [Å] & MgRNA class & Inner atoms & $d$ [Å] & MgRNA class \\
\midrule
\hline 502 & $^{207}$A:O1P & 2.0 & $\mathrm{O_{ph}}$ & $^{207}$A:O1P\newline$^{262}$C:O2P & 2.1\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 503 & -- & -- & -- & $^{114}$A:O2P & 2.0 & $\mathrm{O_{ph}}$ \\
\hline 504 & $^{184}$A:O1P\newline$^{186}$A:O1P\newline$^{187}$A:O2P & 1.8\newline1.8\newline1.9 & \textit{fac}-3$\mathrm{O_{ph}}$ & $^{184}$A:O1P\newline$^{186}$A:O1P\newline$^{187}$A:O2P\newline$^{188}$G:O2P & 2.0\newline2.1\newline2.0\newline2.1 & \underline{\textit{Cis}}-4$\mathrm{O_{ph}}$ \\
\hline 505 & $^{183}$A:O1P\newline$^{184}$A:O2P\newline$^{186}$A:O2P & 2.2\newline2.2\newline2.2 & \textit{fac}-3$\mathrm{O_{ph}}$ & $^{183}$A:O1P\newline$^{184}$A:O2P\newline$^{186}$A:O2P & 2.1\newline2.0\newline2.1 & \textit{fac}-3$\mathrm{O_{ph}}$ \\
\hline 506 & -- & -- & -- & $^{166}$C:O1P\newline$^{168}$U:O1P & 2.2\newline2.2 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 507 & $^{164}$G:O6 & 1.8 & $\mathrm{O_b}$ & $^{163}$G:O2P & 2.1 & $\mathrm{O_{ph}}$ \\
\hline 509 & -- & -- & -- & $^{155}$U:O4 & 2.2 & $\mathrm{O_b}$ \\
\hline 510 & $^{149}$G:O2P & 2.5 & $\mathrm{O_{ph}}$ & $^{149}$G:O2P & 2.1 & $\mathrm{O_{ph}}$ \\
\hline 511 & $^{256}$A:O1P & 2.0 & $\mathrm{O_{ph}}$ & $^{256}$A:O1P\newline$^{273}$U:O1P & 2.2\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 513 & -- & -- & -- & $^{217}$C:O2P & 2.0 & $\mathrm{O_{ph}}$ \\
\hline 514 & $^{214}$A:O2P & 2.1 & $\mathrm{O_{ph}}$ & $^{214}$A:O2P & 2.0 & $\mathrm{O_{ph}}$ \\
\hline 515 & $^{258}$U:O2P\newline$^{305}$U:O2P & 2.3\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ & $^{257}$G:O1P\newline$^{258}$U:O2P\newline$^{260}$C:O2\newline$^{305}$U:O2P & 2.2\newline2.1\newline2.3\newline2.1 & \underline{\textit{Cis}}-3$\mathrm{O_{ph}}$$\mathrm{O_b}$ \\
\hline 516 & -- & -- & -- & $^{258}$U:O1P\newline$^{259}$U:O2P\newline$^{261}$A:O2P & 2.2\newline2.2\newline2.0 & \textit{fac}-3$\mathrm{O_{ph}}$ \\
\hline 517 & $^{259}$U:O1P & 2.2 & $\mathrm{O_{ph}}$ & $^{259}$U:O1P\newline$^{261}$A:O1P & 2.1\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 518 & -- & -- & -- & $^{305}$U:O1P & 2.2 & $\mathrm{O_{ph}}$ \\
\hline 519 & $^{301}$A:O1P\newline$^{302}$A:O2P & 2.2\newline1.8 & \textit{cis}-2$\mathrm{O_{ph}}$ & $^{301}$A:O1P\newline$^{302}$A:O2P & 2.0\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 522 & $^{171}$A:O2P & 2.0 & $\mathrm{O_{ph}}$ & $^{170}$C:O1P\newline$^{171}$A:O2P & 2.2\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 523 & $^{172}$A:O2P & 2.0 & $\mathrm{O_{ph}}$ & $^{172}$A:O2P\newline$^{173}$A:O2P & 2.2\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\hline 526 & $^{306}$A:O1P & 2.3 & $\mathrm{O_{ph}}$ & $^{208}$C:O1P\newline$^{304}$A:O1P\newline$^{306}$A:O1P & 2.2\newline2.1\newline2.1 & \textit{fac}-3$\mathrm{O_{ph}}$ \\
\hline 527 & $^{307}$U:O2P\newline$^{308}$A:O2P & 2.2\newline2.2 & \textit{cis}-2$\mathrm{O_{ph}}$ & $^{307}$U:O2P\newline$^{308}$A:O2P & 2.1\newline2.1 & \textit{cis}-2$\mathrm{O_{ph}}$ \\
\bottomrule
\end{tabularx}

In [135]:
mask

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19    False
20    False
21     True
22     True
23    False
24    False
25     True
26     True
dtype: bool